#!/bin/bash

# check if the PYFILE environment variable is set

if [ -z "$PYFILE" ]; then
	echo "Error: PYFILE environment variable is not set."
	exit 1
fi

# Run the Python script using the environment variable

python3 "$PYFILE"
